import { useState, useRef, ChangeEvent } from "react";
import { 
  Box, 
  Textarea, 
  Input, 
  Button, 
  IconButton, 
  Flex, 
  Image,
} from "@chakra-ui/react";
import { rgba } from "@mantine/core";
import { FiImage, FiX } from "react-icons/fi";
import { postsService } from "@/services/PostsService"; // Adjust import path as needed
import { PostRequestDto } from "@/types/PostInfo"; // Adjust import path as needed
import { toaster } from "../ui/toaster";

export default function CreatePost() {
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [image, setImage] = useState<string | null>(null);
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const bgColor = rgba("#F6F9FE", 1);

  const handleImageUpload = (e: ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setImageFile(file);
      const reader = new FileReader();
      reader.onload = () => {
        setImage(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleRemoveImage = () => {
    setImage(null);
    setImageFile(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  const handleSubmit = async () => {
    if (!content && !image) return;

    setIsSubmitting(true);
    
    try {
      const postData: PostRequestDto = {
        postId: 0, // Will be generated by backend
        title,
        content,
        authorId: 1, // Replace with actual user ID from auth context
        status: "PUBLISHED", // Or whatever default status you use
        imageFile: imageFile || undefined
      };

      const postId = await postsService.createPost(postData);
      console.log("Post created with ID:", postId);

      toaster.create({
        title: "Post created successfully",
        type: "success",
        duration: 3000,
        closable: true,
      });

      // Reset form
      setTitle("");
      setContent("");
      setImage(null);
      setImageFile(null);
      if (fileInputRef.current) {
        fileInputRef.current.value = "";
      }
    } catch (error) {
      toaster.create({
        title: "Failed to create post",
        description: error instanceof Error ? error.message : "Unknown error occurred",
        type: "error",
        duration: 5000,
        closable: true,
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Box 
      p={4} 
      borderRadius="lg" 
      bg={bgColor}
      boxShadow="sm"
      width="100%"
      maxW="600px"
    >
      <Input
        placeholder="Title (optional)"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        mb={3}
        variant="flushed"
        fontSize="lg"
        fontWeight="semibold"
      />
      <Textarea
        placeholder="What's happening?"
        value={content}
        onChange={(e) => setContent(e.target.value)}
        resize="none"
        minH="120px"
        fontSize="md"
      />
      
      {image && (
        <Box mt={3} position="relative">
          <Image
            src={image}
            alt="Post preview"
            borderRadius="md"
            maxH="300px"
            objectFit="cover"
            width="100%"
          />
          <IconButton
            aria-label="Remove image"
            size="sm"
            position="absolute"
            top={2}
            right={2}
            onClick={handleRemoveImage}
            bg="blackAlpha.600"
            color="white"
            _hover={{ bg: "blackAlpha.800" }}
          >
            <FiX />
          </IconButton>
        </Box>
      )}

      <Flex mt={3} justify="space-between" align="center">
        <input
          type="file"
          accept="image/*"
          onChange={handleImageUpload}
          ref={fileInputRef}
          hidden
        />
        <IconButton
          aria-label="Upload image"
          onClick={() => fileInputRef.current?.click()}
          variant="ghost"
          colorScheme="blue"
        >
          <FiImage />
        </IconButton>
        <Button
          colorScheme="blue"
          borderRadius="full"
          onClick={handleSubmit}
          loading={isSubmitting}
          disabled={(!content && !image) || isSubmitting}
        >
          Post
        </Button>
      </Flex>
    </Box>
  );
}